// Type declarations for @itslil/lil2-mdast-util-from-markdown. Generated by lilscript-work/lil2/release/types.mjs.
/**
 * mdast as positional columns: the parser's own arrays, indexed by node id. Node 0 is the root.
 *
 * A node's kind is `kind[node]`, one of the `K_*` constants (`/constants`). Its children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column.
 * Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 *
 * Strings per kind (`s1` / `s2` / `s3`): text, html, inlineCode, math, inlineMath: value; code: value / lang /
 * meta; definition and link: url / title; image: url / title / alt; imageReference: alt. `flags` (`N_*` bits)
 * says which optional ones are set. `num` is a heading's depth, a list's start, a reference's type (0 shortcut,
 * 1 collapsed, 2 full) or, for a table, the offset of its alignments in `aux` (a count, then one `ALIGN_*` per
 * column). `identifier[node]` is an id into `identifiers` (-1: none).
 */
export type MdastColumns = readonly [
  kind: readonly number[],
  flags: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  num: readonly number[],
  s1: readonly string[],
  s2: readonly string[],
  s3: readonly string[],
  identifier: readonly number[],
  label: readonly string[],
  lineStarts: readonly number[],
  identifiers: readonly string[],
  aux: readonly number[],
]

/** Parses markdown (CommonMark) to mdast columns, the same tree mdast-util-from-markdown 2 builds. */
export declare function fromMarkdown(value: string): MdastColumns
